# Exclude a variety of commonly ignored directories.
exclude = [".git", ".pyenv", ".pytest_cache", ".pytype"]

line-length = 108
indent-width = 4


[lint]
select = ["A", "ANN", "ARG", "B", "COM", "FAST", "I", "TID"]
ignore = [
	"ANN401", # any-type
	"B002",   # unary-prefix-increment-decrement
	"B031",   # reuse-of-groupby-generator
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[lint.flake8-tidy-imports.banned-api]
"typing.Iterable".msg = "Use collections.abc.Iterable"
"typing.Iterator".msg = "Use collections.abc.Iterator"
"typing.Sequence".msg = "Use collections.abc.Sequence"
"typing.Mapping".msg = "Use collections.abc.Mapping"
"typing.MutableMapping".msg = "Use collections.abc.MutableMapping"

[lint.isort]
force-wrap-aliases = true
known-local-folder = ["app"]

[lint.pycodestyle]
max-line-length = 100

[format]
indent-style = "tab"
quote-style = "single"
docstring-code-format = true
